#!/usr/bin/env python3
"""Four-outcome pytest gate — exit 0 alone does not mean a suite ran.

WHY. pytest collapses four materially different outcomes into two exit
statuses, and two of the four look green or trivially red while meaning
"this suite verified nothing":

    exit 4  usage error — typically a path argument that does not exist.
            This is precisely how the integration job was red for the wrong
            reason in Task 1: it named test paths that were never committed,
            so the job failed as a *usage* error, indistinguishable from a
            working gate unless someone read the exit code.
    exit 5  no tests collected at all.
    exit 0  green — or "every collected test was skipped", the dangerous
            case: a wholly-skipped module reports ``2 skipped``, exit 0, and
            looks identical to a pass while proving nothing.
    exit 1  at least one test executed and failed.

Only "tests ran and passed" is acceptable, and only when a known MINIMUM
number of tests actually EXECUTED. This gate separates those outcomes and
enforces the floor, counting EXECUTED tests (ran to a pass/fail verdict),
not collected ones — a wholly-skipped module counts as zero executed and
fails the floor. See docs/ADR/0001 register entry 9 and ARCHITECTURE §6.

Usage:
    uv run python tools/pytest_gate.py <path>... [--min-executed N] [-- ARGS...]

Everything after the first bare ``--`` is passed to pytest verbatim (e.g.
``-m "not slow"``). The split happens before this gate's own argument
parsing, so option order on the left of ``--`` is free.

Exit status:
    0  suite passed AND executed >= --min-executed
    1  any other suite outcome (usage error, nothing collected, nothing
       executed, floor unmet, test failures, or any other nonzero pytest exit)
    2  gate-internal failure (a nonzero run produced no usable JUnit XML)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from collections.abc import Sequence
from pathlib import Path
from typing import Final

# pytest's documented exit codes that this gate must DISTINGUISH rather than
# collapse. Named constants, not magic numbers: the number is meaningless
# without the name, and the name is the whole point of the fix.
EXIT_USAGE: Final[int] = 4
EXIT_NO_TESTS_COLLECTED: Final[int] = 5

GATE_GREEN: Final[int] = 0
GATE_RED: Final[int] = 1
GATE_INTERNAL_ERROR: Final[int] = 2

_MIN_EXECUTED_FLOOR: Final[int] = 1
_ARG_SEPARATOR: Final = "--"
_TAG_TESTCASE: Final = "testcase"
_TAG_SKIPPED: Final = "skipped"
_TAG_FAILURE: Final = "failure"
_TAG_ERROR: Final = "error"


def _counts(junit_path: Path) -> tuple[int, int, int, int] | None:
    """Parse a pytest JUnit XML file into (total, skipped, failed, errored).

    ``total`` counts every ``<testcase>``, including skipped ones — that is
    "reported", not "executed". The caller computes executed = total - skipped.
    Returns None when the file is missing or unparseable, which is a
    gate-internal failure: a run that produced no XML cannot be counted and
    must not be treated as either green or red-by-suite.
    """
    if not junit_path.is_file():
        return None
    try:
        # S314 suppressed: this XML is generated by this gate's own pytest
        # subprocess into a private temporary directory. It is not
        # attacker-controlled input; the only "untrusted" aspect is a crashed
        # pytest writing a truncated file, which ParseError already handles.
        root = ET.parse(junit_path).getroot()  # noqa: S314
    except ET.ParseError:
        return None
    cases = list(root.iter(_TAG_TESTCASE))
    skipped = sum(1 for case in cases if case.find(_TAG_SKIPPED) is not None)
    failed = sum(1 for case in cases if case.find(_TAG_FAILURE) is not None)
    errored = sum(1 for case in cases if case.find(_TAG_ERROR) is not None)
    return len(cases), skipped, failed, errored


def _red(message: str) -> int:
    print(f"[pytest-gate] RED: {message}", file=sys.stderr)
    return GATE_RED


def _green(executed: int, skipped: int, failed: int, errored: int, minimum: int) -> int:
    print(
        f"[pytest-gate] GREEN: executed={executed} skipped={skipped} "
        f"failed={failed} errors={errored} (min-executed={minimum})"
    )
    return GATE_GREEN


def main(argv: Sequence[str] | None = None) -> int:  # noqa: PLR0911
    """Run pytest under the four-outcome gate. See module docstring.

    PLR0911 (7 returns) accepted deliberately: this function's entire job
    is to enumerate the suite outcomes one return per outcome, so that a
    reader can see all four (plus the two internal errors) side by side.
    Collapsing them into a lookup table would hide the failure modes this
    gate exists to distinguish — the same reasoning as ssrf.py's
    PLR0911/PLR0912 suppression.
    """
    raw = list(sys.argv[1:]) if argv is None else list(argv)

    # Split at the FIRST bare "--" before argparse sees anything. This is done
    # manually because argparse's REMAINDER cannot do it: a REMAINDER
    # positional swallows every argument after the first one it does not
    # recognise, including this gate's own --min-executed when it follows the
    # paths. That exact bug was caught by the four-outcome demo run on this
    # very tool: "--min-executed 5" was forwarded to pytest, which exited 4
    # and produced a misleading usage-error message.
    if _ARG_SEPARATOR in raw:
        split_at = raw.index(_ARG_SEPARATOR)
        gate_args, extra = raw[:split_at], raw[split_at + 1 :]
    else:
        gate_args, extra = raw, []

    parser = argparse.ArgumentParser(
        prog="pytest_gate",
        description="Run pytest and require a minimum number of EXECUTED tests.",
    )
    parser.add_argument("paths", nargs="+", help="test paths passed to pytest")
    parser.add_argument(
        "--min-executed",
        type=int,
        default=_MIN_EXECUTED_FLOOR,
        help="minimum tests that must run to a pass/fail verdict (default: 1)",
    )
    args = parser.parse_args(gate_args)

    if args.min_executed < _MIN_EXECUTED_FLOOR:
        return _red(f"--min-executed must be >= {_MIN_EXECUTED_FLOOR}, got {args.min_executed}")

    with tempfile.TemporaryDirectory(prefix="neptiq-pytest-gate-") as tmp_name:
        junit_path = Path(tmp_name) / "junit.xml"
        command = [
            sys.executable,
            "-m",
            "pytest",
            *args.paths,
            *extra,
            f"--junitxml={junit_path}",
        ]
        print(f"[pytest-gate] {' '.join(command)}", file=sys.stderr)
        completed = subprocess.run(command, check=False)
        counts = _counts(junit_path)

    # Outcome 1: usage error. The classic cause is a path that does not exist —
    # the exact defect the integration job had. It is reported as its own
    # failure mode, not folded into "tests failed".
    if completed.returncode == EXIT_USAGE:
        return _red(
            "pytest usage error (exit 4) — usually a path argument that does "
            f"not exist: {' '.join(args.paths)}"
        )

    # Outcome 2: nothing collected. An empty suite is a broken suite.
    if completed.returncode == EXIT_NO_TESTS_COLLECTED:
        return _red(f"no tests collected (exit 5) under: {' '.join(args.paths)}")

    if counts is None:
        print(
            f"[pytest-gate] INTERNAL: pytest exited {completed.returncode} "
            "without usable JUnit XML — the run cannot be counted",
            file=sys.stderr,
        )
        return GATE_INTERNAL_ERROR

    total, skipped, failed, errored = counts
    executed = total - skipped

    if completed.returncode != GATE_GREEN:
        return _red(
            f"pytest exited {completed.returncode} "
            f"(executed={executed} skipped={skipped} failed={failed} "
            f"errors={errored})"
        )

    # Outcome 3: green exit but nothing actually ran — all skipped (or every
    # test deselected by a -m filter, which leaves no testcase entries either).
    # This is the vacuous pass; the floor is what makes it impossible.
    if executed < args.min_executed:
        return _red(
            f"only {executed} test(s) EXECUTED (total={total} skipped={skipped}) "
            f"but the floor is {args.min_executed}. A suite whose tests are all "
            "skipped or deselected is RED: exit 0 with nothing executed proves "
            "nothing (ADR 0001 register entry 9)."
        )

    # Outcome 4: genuinely passing, with the executed floor met.
    return _green(executed, skipped, failed, errored, args.min_executed)


if __name__ == "__main__":
    sys.exit(main())
